### ISSUE TITLE
dev-master: `figcaption` at a strange position

### ISSUE THREAD

**Issue by dgrammlich** [daniellienert/DL.Gallery#3] opened 2016-11-08 17:53 UTC
Hey @daniellienert,

I use the Justified gallery on my website, but the `figcaption` of all pictures included in the gallery is seen on the top left of the gallery behind the pictures:
![screenshot from 2016-11-08 18-47-18](https://cloud.githubusercontent.com/assets/5312377/20110226/cc94de3a-a5e3-11e6-84b1-5f8bef40f4f9.png)

See also https://grammheimlich.de/de/galerie.html.

Did I miss something, or is it just under development? Thanks in advance for your help. :)

**Comment by daniellienert** [comment] 2016-12-23 11:26
Hey @dgrammlich,

thanks for reporting. The issue is fixed with: https://github.com/daniellienert/DL.Gallery/commit/98de58ddb4ef092c2b2a6fa10ee4774f12767be4

**Closed as completed by daniellienert** 2016-12-23 11:27 UTC
